Removed obsolete 'bitcoin' script and change numerous bash scripts to ensure 'echo' commands use double quotes and for errors use 'exit 1'.

diff --git a/src/ciyam_restore_all b/src/ciyam_restore_all
--- a/src/ciyam_restore_all
+++ b/src/ciyam_restore_all
@@ -33,6 +33,8 @@ else
 
  if [ "$has_meta" = "" ]; then
   echo "Error: Missing application backup metadata."
+
+  exit 1
  else
   ./ciyam_restore Meta meta
 
@@ -56,7 +58,9 @@ else
   done
 
   if [ $tries -gt $limit ]; then
-    echo "Error: Unexpected server not available."
+   echo "Error: Unexpected server not available."
+
+   exit 1
   else
    if [ ! "$app_names" = "" ]; then
     ./restore Meta $app_names
diff --git a/src/create_demo_application b/src/create_demo_application
--- a/src/create_demo_application
+++ b/src/create_demo_application
@@ -5,10 +5,12 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ $# -lt 2 ]; then
- echo Usage: create_demo_application [model name] [demo name]
+ echo "Usage: create_demo_application [model name] [demo name]"
 else
  if [ ! -f create_demo_$2_application.cin ]; then
-  echo Error: File 'create_demo_$2_application.cin' does not exist.
+  echo "Error: File 'create_demo_$2_application.cin' does not exist."
+
+  exit 1
  else
   export CIYAM_MODEL=$1
   ./ciyam_client -quiet -no_prompt < create_demo_$2_application.cin
diff --git a/src/create_module b/src/create_module
--- a/src/create_module
+++ b/src/create_module
@@ -5,7 +5,7 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ $# -lt 1 ]; then
- echo Usage: create_module [[-rdbms]] [module name]
+ echo "Usage: create_module [[-rdbms]] [module name]"
 else
  mod_name=$1
  is_rdbms=
@@ -16,7 +16,9 @@ else
  fi
 
  if [ -f $mod_name.cpp ]; then
-  echo Error: Module \'$mod_name\' already exists.
+  echo "Error: Module '$mod_name' already exists."
+
+  exit 1
  else
 
   if [ "$is_rdbms" = "1" ]; then
@@ -39,7 +41,9 @@ else
      ./genmodule $mod_name
     fi
    else
-    echo Error: Running script \'$mod_name.cin\' failed to create \'$mod_name.sio\'.
+    echo "Error: Running script '$mod_name.cin' failed to create '$mod_name.sio'."
+
+    exit 1
    fi
   fi
  fi
diff --git a/src/gen_app_script b/src/gen_app_script
--- a/src/gen_app_script
+++ b/src/gen_app_script
@@ -21,7 +21,9 @@ else
  rm -f $tmp_file
 
  if [ "$CIYAM_APPLICATION" = "" ]; then
-  echo "Error: Unknown application '$1'."
+  echo "Error: Unknown application name '$1'."
+
+  exit 1
  else
   ./ciyam_client -quiet -no_prompt -no_stderr -exec="<gen_app_script.cin $CIYAM_APPLICATION"
  fi
diff --git a/src/genfcgi b/src/genfcgi
--- a/src/genfcgi
+++ b/src/genfcgi
@@ -5,24 +5,30 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ $# -lt 2 ]; then
- echo Usage: genfcgi [app name] [app dir] [[web dir]]
+ echo "Usage: genfcgi [app name] [app dir] [[web dir]]"
 else
  if [ $# -gt 2 ]; then
   export WEBDIR=$3
  fi
  if [ "$WEBDIR" = "" ]; then
-  echo Error: Missing environment variable 'WEBDIR'.
+  echo "Error: Missing environment variable 'WEBDIR'."
+
+  exit 1
  else
   directory=$WEBDIR/$2
 
   if [ ! -f $1.app.vars.xrep ]; then
-   echo Error: File \'$1.app.vars.xrep\' does not exist.
+   echo "Error: File '$1.app.vars.xrep' does not exist."
+
+   exit 1
   else
    if [ ! -d $directory ]; then
     ./setup $1 $2 $3
    fi
    if [ ! -f $directory/activate.htms ]; then
-    echo Error: File \'$directory/activate.htms\' does not exist.
+    echo "Error: File '$directory/activate.htms' does not exist."
+
+    exit 1
    else
     tmp_file=$(mktemp --suffix ".tmp")
 
diff --git a/src/init b/src/init
--- a/src/init
+++ b/src/init
@@ -5,7 +5,7 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ $# -lt 1 ]; then
- echo Usage: init [model name] [[app name]]
+ echo "Usage: init [model name] [[app name]]"
 else
  had_error=
 
@@ -19,25 +19,24 @@ else
  if [ "$2" = "ciyam" ]; then
   export CIYAM_TEST_STORAGE=1
  elif [ "$WEBDIR" = "" ]; then
-  had_error=true
-  echo Error: Missing environment variable 'WEBDIR'.
+  echo "Error: Missing environment variable 'WEBDIR'."
+
+  exit 1
  fi
 
- if [ ! "$had_error" = "true" ]; then
-  rm -f $CIYAM_STORAGE.log $CIYAM_STORAGE.tlg $CIYAM_STORAGE.dat $CIYAM_STORAGE.idx $CIYAM_STORAGE.hdr >/dev/null
-  ./ciyam_server -quiet -no_auto -no_peers &
+ rm -f $CIYAM_STORAGE.log $CIYAM_STORAGE.tlg $CIYAM_STORAGE.dat $CIYAM_STORAGE.idx $CIYAM_STORAGE.hdr >/dev/null
+ ./ciyam_server -quiet -no_auto -no_peers &
 
-  sleep 2
-  ./ciyam_client -quiet -no_prompt -connect_retries=10 < init.cin
-  touch ciyam_server.stop
+ sleep 2
+ ./ciyam_client -quiet -no_prompt -connect_retries=10 < init.cin
+ touch ciyam_server.stop
 
-  for i in {1..20}
-  do
-   sleep 0.5
-   if [ ! -f ciyam_server.stop ]; then
-    break;
-   fi
-  done
+ for i in {1..20}
+ do
+  sleep 0.5
+  if [ ! -f ciyam_server.stop ]; then
+   break;
+  fi
+ done
 
- fi
 fi
diff --git a/src/install_fcgi b/src/install_fcgi
--- a/src/install_fcgi
+++ b/src/install_fcgi
@@ -5,21 +5,27 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ $# -lt 2 ]; then
- echo Usage: install_fcgi [FCGI w/o ext] [app dir] [[extra files]]
+ echo "Usage: install_fcgi [FCGI w/o ext] [app dir] [[extra files]]"
 else
  tmp=$1.fcgi
  args=$1.fcgi
  directory=$WEBDIR/$2
 
  if [ ! -f $1 ]; then
-  echo Error: File \'$1\' does not exist.
+  echo "Error: File '$1' does not exist."
+
+  exit 1
  else
   cp $1 $1.fcgi
 
   if [ ! -f $args ]; then
-   echo Error: File \'$args\' does not exist.
+   echo "Error: File '$args' does not exist."
+
+   exit 1
   elif [ ! -f $directory/fcgi.sio ]; then
-   echo Error: File \'$directory/fcgi.sio\' does not exist.
+   echo "Error: File '$directory/fcgi.sio' does not exist."
+
+   exit 1
   else
    shift
    shift
diff --git a/src/install_module b/src/install_module
--- a/src/install_module
+++ b/src/install_module
@@ -5,15 +5,19 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ $# -lt 2 ]; then
- echo Usage: install_module [module name] [app dir] [[module alias]]
+ echo "Usage: install_module [module name] [app dir] [[module alias]]"
 else
  export alias=$3
  export directory=$WEBDIR/$2
 
  if [ ! -f $1.fcgi.sio ]; then
-  echo Error: File \'$1.fcgi.sio\' does not exist.
+  echo "Error: File '$1.fcgi.sio' does not exist."
+
+  exit 1
  elif [ ! -f $directory/fcgi.sio ]; then
-  echo Error: File \'$directory/fcgi.sio\' does not exist.
+  echo "Error: File '$directory/fcgi.sio' does not exist."
+
+  exit 1
  else
   cp $1.fcgi.sio $directory
   chmod a+r $directory/$1.fcgi.sio
diff --git a/src/install_test_fcgi b/src/install_test_fcgi
--- a/src/install_test_fcgi
+++ b/src/install_test_fcgi
@@ -5,23 +5,33 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ "$WEBDIR" = "" ]; then
- echo Error: Missing environment variable \'WEBDIR\'.
+ echo "Error: Missing environment variable 'WEBDIR'."
+
+ exit 1
 else
  if [ ! -f test_fcgi ]; then
-  echo Error: File \'test_fcgi\' does not exist \(not built?\).
+  echo "Error: File 'test_fcgi' does not exist (not built?)."
+
+  exit 1
  else
   if [ ! -f test_fcgi.html ]; then
-   echo Error: File \'test_fcgi.html\' does not exist.
+   echo "Error: File 'test_fcgi.html' does not exist."
+
+   exit 1
   else
    cp test_fcgi.html "$WEBDIR"
    if [ ! -f "$WEBDIR/test_fcgi.html" ]; then
-    echo Error: Unable to copy \'test_fcgi.html\' to "$WEBDIR".
+    echo "Error: Unable to copy 'test_fcgi.html' to '$WEBDIR'."
+
+    exit 1
    else
     cp test_fcgi "$WEBDIR/test_fcgi.fcgi"
     if [ ! -f "$WEBDIR/test_fcgi.fcgi" ]; then
-     echo Error: Unable to copy \'test_fcgi.fcgi\' to "$WEBDIR".
+     echo "Error: Unable to copy 'test_fcgi.fcgi' to '$WEBDIR'."
+
+     exit 1
     else
-     echo Installed. Use http://localhost/test_fcgi.html to test.
+     echo "Installed. Use http://localhost/test_fcgi.html to test."
     fi
    fi
   fi
diff --git a/src/prepare_release b/src/prepare_release
--- a/src/prepare_release
+++ b/src/prepare_release
@@ -20,10 +20,16 @@ rm_src=
 
 if [ "$1" = "-remove_source" ]; then
  rm_src=1
+
+ if [ "$CIYAM_CPP_OPTS" != "" ]; then
+  echo "Error: Found CIYAM_CPP_OPTS (unset if really wanting to remove source code)."
+
+  exit 1
+ fi
 elif [ ! "$1" = "-keep_source" ]; then
  echo "Error: Invalid option '$1' for prepare_release"
 
- exit
+ exit 1
 fi
 
 using_service=
@@ -49,7 +55,7 @@ if [ "$using_service" = "" ]; then
   echo "Error: Timed out trying to stop the CIYAM application server (is not running?)."
   rm -f ciyam_server.stop
 
-  exit
+  exit 1
  fi
 else
  sudo systemctl stop ciyam
@@ -59,6 +65,7 @@ make strip
 
 if [ "$using_service" = "" ]; then
  ./ciyam_server &
+ sleep 1
 else
  sudo systemctl daemon-reload
  sudo systemctl start ciyam
@@ -66,6 +73,10 @@ else
 fi
 
 make release
+
+if [ $? -ne 0 ]; then
+ exit
+fi
 
 if [ "$rm_src" = "1" ]; then
  ./reconstruct_meta okay
diff --git a/src/reinstall_packages b/src/reinstall_packages
--- a/src/reinstall_packages
+++ b/src/reinstall_packages
@@ -5,15 +5,19 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ $# -ne 1 ]; then
- echo Usage: reinstall_packages [okay]
+ echo "Usage: reinstall_packages [okay]"
 else
  if [ ! "$1" = "okay" ]; then
   echo "Error: Invalid argument '$1' for 'reinstall_packages'."
+
+  exit 1
  else
   ./ciyam_client -quiet -no_prompt < get_acyclic_package_types.cin
 
   if [ ! -f packages.acyclic.lst ]; then
-   echo Error: File 'packages.acyclic.lst' does not exist.
+   echo "Error: File 'packages.acyclic.lst' does not exist."
+
+   exit 1
   else
    ./ciyam_client -quiet -no_prompt < recreate_meta.cin
    ./xrep @reinstall_packages.cin.xrep packages=@packages.acyclic.lst >reinstall_packages.cin
diff --git a/src/remove_fcgi b/src/remove_fcgi
--- a/src/remove_fcgi
+++ b/src/remove_fcgi
@@ -5,13 +5,15 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ $# -lt 1 ]; then
- echo Usage: remove_fcgi [app dir] [[web dir]]
+ echo "Usage: remove_fcgi [app dir] [[web dir]]"
 else
  if [ $# -gt 1 ]; then
   export WEBDIR=$2
  fi
  if [ "$WEBDIR" = "" ]; then
-  echo Error: Missing environment variable 'WEBDIR'.
+  echo "Error: Missing environment variable 'WEBDIR'."
+
+  exit 1
  else
   if [ -d $WEBDIR/$1 ]; then
    if [ -f $WEBDIR/$1/upload.kill.sh ]; then
diff --git a/src/remove_module b/src/remove_module
--- a/src/remove_module
+++ b/src/remove_module
@@ -16,7 +16,9 @@ else
  fi
 
  if [ ! "$is_rdbms" = "1" ] && [ ! -f $mod_name.cpp ]; then
-  echo Error: Module \'$mod_name\' does not exist.
+  echo "Error: Module '$mod_name' does not exist."
+
+  exit 1
  else
   ./xrep @remove_module.xrep name=$mod_name modules=@modules.lst >modules.lst.new
 
diff --git a/src/restore_identity b/src/restore_identity
--- a/src/restore_identity
+++ b/src/restore_identity
@@ -5,7 +5,9 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ "$WEBDIR" = "" ]; then
-  echo Error: Missing environment variable 'WEBDIR'.
+ echo "Error: Missing environment variable 'WEBDIR'."
+
+ exit 1
 else
  restored_any=
  restored_meta=
diff --git a/src/search_nonces b/src/search_nonces
--- a/src/search_nonces
+++ b/src/search_nonces
@@ -5,10 +5,12 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ $# -lt 3 ]; then
- echo Usage: search_nonces [data] [start num] [num searches] [[search range]]
+ echo "Usage: search_nonces [data] [start num] [num searches] [[search range]]"
 else
  if [ "$4" = "0" ] || [ "$4" = "1" ]; then
-  echo Error: If supplied then 'search range' must be greater than or equal to 2.
+  echo "Error: If supplied then 'search range' must be greater than or equal to 2."
+
+  exit 1
  else
   export CIYAM_DATA=$1
   export CIYAM_START_NUM=$2
diff --git a/src/setup b/src/setup
--- a/src/setup
+++ b/src/setup
@@ -5,14 +5,16 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ $# -lt 2 ]; then
- echo Usage: setup [app name] [app dir] [[web dir]]
+ echo "Usage: setup [app name] [app dir] [[web dir]]"
 else
  if [ $# -gt 2 ]; then
   export WEBDIR=$3
  fi
 
  if [ "$WEBDIR" = "" ]; then
-  echo Error: Missing environment variable 'WEBDIR'.
+  echo "Error: Missing environment variable 'WEBDIR'."
+
+  exit 1
  else
   [ -d $WEBDIR/$2 ] ||
   {
diff --git a/src/test_xrep_spec b/src/test_xrep_spec
--- a/src/test_xrep_spec
+++ b/src/test_xrep_spec
@@ -29,7 +29,9 @@ else
  fi
 
  if [ "$spec_args" = "" ]; then
-   echo "Error: Missing spec arguments for 'test_xrep_spec'."
+  echo "Error: Missing spec arguments for 'test_xrep_spec'."
+
+  exit 1
  else
   ./xrep @test_spec.xrep model_name=Model object=$spec section=$section "${spec_args[@]}"
  fi
diff --git a/src/upgrade_prototype b/src/upgrade_prototype
--- a/src/upgrade_prototype
+++ b/src/upgrade_prototype
@@ -5,10 +5,14 @@
 # in the root project directory or http://www.opensource.org/licenses/mit-license.php.
 
 if [ "$WEBDIR" = "" ]; then
-  echo "Error: Missing environment variable 'WEBDIR'."
+ echo "Error: Missing environment variable 'WEBDIR'."
+
+ exit 1
 else
  if [ ! -f ciyam_server.sid.sav ]; then
   echo "Error: Saved identity (ciyam_server.sid.sav) was not found."
+
+  exit 1
  else
   ./restore_identity > /dev/null
   sudo systemctl restart ciyam
