CIYAM Open Developrs Task #T00000

diff --git a/src/ciyam_install b/src/ciyam_install
--- a/src/ciyam_install
+++ b/src/ciyam_install
@@ -1,16 +1,25 @@
-#! /bin/sh
-#
-# Installation script for ciyam_server (should generally run as su).
-#
-echo Installing ciyam_server...
-./ciyamd stop
-cp ciyam_server /usr/bin
-if [ -d /usr/lib64 ]; then
- cp ciyam_base.so /usr/lib64
-else
- cp ciyam_base.so /usr/lib
+#!/bin/bash
+
+if [ `whoami` != "root" ]
+then
+	echo "Run this script as root."
+	exit 1
 fi
-cp ciyamd /etc/init.d
-insserv -r /etc/init.d/ciyamd
-insserv /etc/init.d/ciyamd
-./ciyamd start
+
+ps ax | grep ciyamd | awk '{print $1}' | xargs kill 2>/dev/null
+
+cat .git/config | grep github.com/ciyam/ciyam.git 2>&1 > /dev/null
+GITCHECK=$?
+if [ "$GITCHECK" != "0" ]
+then
+	echo 'ERROR: the current directory isnt the ciyam git!'
+	exit 1
+fi
+
+DESTPATH="/usr/local/src/ciyam"
+mkdir -p "${DESTPATH}"
+cp -R src/ "${DESTPATH}"
+ln -s "${DESTPATH}/ciyam/ciyamd" "/usr/local/bin/"
+ln -s "${DESTPATH}/ciyam/ciyam_base.so" "/usr/local/lib/"
+
+exit 0
